### PR TITLE
Release 18.01 cleanup of ISA datatype enhancements

### PR DESCRIPTION
**Pull request by djcomlab**
Release 18.01 cleanup of ISA datatype enhancements.

I did a quick test building and running `container-galaxy-k8s-runtime` with `release_18.01_plus_isa_runnerRJ_clean` and seems to work as expected.

### CODE REVIEW

**Comment by pcm32** [comment]
I wouldn't do a merge here... I would just use this branch instead. I guess then what we need to do is a change in container-galaxy-runtime to point to the new branch. Thanks @djcomlab for cleaning this up!!

**Comment by pcm32** [comment]
or we can revert the merge on the other branch and then merge this....

**Comment by djcomlab** [comment]
Whatever works best! I'm officially on vacation now! :joy:

**Comment by pcm32** [comment]
Nah, is easier just to use this branch now from our container.

**Comment by pcm32** [comment]
Yes, you and @ilveroluca, who laughs at us for having to fix this by sending pictures from the beach.... enjoy guys!

**Pull request closed without merging**
