### PR TITLE
Add nmrML datatype.

### PR DESCRIPTION
**Pull request by pkrog**
An nmrML data type for NMR tools and workflows.

### CODE REVIEW

**Review by pcm32 — APPROVED** [review]
LGTM!

**Comment by pcm32** [comment]
Please squash when merging!

**Comment by ilveroluca** [comment]
Let's remember to add the `<datatype>` entry to the `datatypes_conf.xml` file in [container-galaxy-k8s-runtime](https://github.com/phnmnl/container-galaxy-k8s-runtime)

**Comment by pcm32** [comment]
@pkrog from here, can you please delete the branch from where you merged? Thanks, to avoid branch proliferation.

**Comment by pkrog** [comment]
I deleted it already.

**Pull request merged**
